baseurl = ""
title = "dProc"
theme = "hugo-coder"
themesDir = "../themes"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true
relativeURLs = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[params]
    # author = "Max Franks"
    info = "A data processing library written in Go"
    description = "dProc features Actor-like functionality and is similar to Flow-based programming"
    keywords = "blog,project,data,go"
    avatarurl = "images/dProc_small.svg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    # footercontent = "Enter a text here."

    hidecredits = false
    hidecopyright = false

    rtl = false

    # math = true
    # custom_css = ["css/custom.css"]

    godoc = "https://godoc.org/github.com/eliquious/dproc"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/eliquious/dproc"

# Menu links
[[menu.main]]
    name = "Docs"
    weight = 1
    url  = "https://godoc.org/github.com/eliquious/dproc"
[[menu.main]]
    name = "Articles"
    weight = 2
    url = "/articles/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
